### ISSUE TITLE
 A drawer was already declared for 'position="start"'

### ISSUE THREAD

**Issue by alkahtani** [adminmart/modernize-angular-free#1]
I'm encountering an error while testing the bootstrapping functionality across various device screen sizes using Chrome Developer Tools.

 Steps to Reproduce
1. Open the project in a web browser (Chrome)
2. Access Chrome Developer Tools
3. Use the device toolbar to simulate different screen sizes
4. Attempt to test the bootstrapping functionality

 Expected Behavior
The bootstrapping should work correctly across all simulated device screen sizes.

 Actual Behavior
An error occurs during the testing process. 
`core.mjs:6620 ERROR Error: A drawer was already declared for 'position="start"'
    at throwMatDuplicatedDrawerError (sidenav.mjs:46:11)
    at sidenav.mjs:790:21
    at Array.forEach (<anonymous>)
    at QueryList.forEach (core.mjs:7165:23)
    at MatSidenavContainer._validateDrawers (sidenav.mjs:781:23)
    at Object.next (sidenav.mjs:627:18)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at subscribe.innerComplete (mergeInternals.js:25:28)`

 Additional Information
- Browser: Google Chrome (version: please specify)
- Chrome DevTools version: (if known)

 Screenshots

![error](https://github.com/user-attachments/assets/9f93206d-e3ef-4c24-9cdc-cd59a4dc1955)

---

I'd like to express my gratitude for this licensed product. It provides an excellent foundation for various projects, and I appreciate the hard work that has gone into its development.

**Comment by adminmart** [comment]
Hi,

Thanks for the contact, as we already aware about this problem, we also
talked with angular github issue. but as per their code, we can only use
drawer 1 time in same position, like if i use with position start then if i
use it again with same position it will throw this type of error.

as we used different drower for mobile and desktop view. so either the
solution is to drop the use of their default drawer and make our own and
either to ignore this error.

Also please create a ticket regarding other issues, if you face it.

Thanks
